package com.sc.android.chestwork.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sc.android.chestwork.db.CloseBean;

import com.sc.android.chestwork.db.CloseBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig closeBeanDaoConfig;

    private final CloseBeanDao closeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        closeBeanDaoConfig = daoConfigMap.get(CloseBeanDao.class).clone();
        closeBeanDaoConfig.initIdentityScope(type);

        closeBeanDao = new CloseBeanDao(closeBeanDaoConfig, this);

        registerDao(CloseBean.class, closeBeanDao);
    }
    
    public void clear() {
        closeBeanDaoConfig.clearIdentityScope();
    }

    public CloseBeanDao getCloseBeanDao() {
        return closeBeanDao;
    }

}
